# Generated by Django 3.0.4 on 2020-03-22 05:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scania_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='annual_target',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=5), default=(0.0, 0.0), size=None),
            preserve_default=False,
        ),
    ]
