# Generated by Django 3.0.4 on 2020-03-22 06:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scania_app', '0002_sector_annual_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='children_in_preschool',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=(0, 0), size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='tax_rate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=5), default=(0.0, 0.0), size=None),
            preserve_default=False,
        ),
    ]
