# Generated by Django 3.0.4 on 2020-03-23 15:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scania_app', '0003_auto_20200322_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='elementary_students',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=(0, 0), size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='high_school_students',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=(0, 0), size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='junior_high_students',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=(0, 0), size=None),
            preserve_default=False,
        ),
    ]
