# Generated by Django 3.0.4 on 2020-03-29 05:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scania_app', '0004_auto_20200323_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='expenses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=5), default=(0.0, 0.0), size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='income',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=5), default=(0.0, 0.0), size=None),
            preserve_default=False,
        ),
    ]
