# Generated by Django 3.0.4 on 2020-03-30 03:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scania_app', '0005_auto_20200329_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='average_house_prices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=(0, 0), size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='caretaker_per_child',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=5), default=(0.0, 0.0), size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='deaths',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=(0, 0), size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='emmigration',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=(0, 0), size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='immigration',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=(0, 0), size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='newborns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=(0, 0), size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='number_of_houses_sold',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=(0, 0), size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='number_of_millioner_income_earners',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=(0, 0), size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='pension_obligation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=5), default=(0.0, 0.0), size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='population_median_income',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=5), default=(0.0, 0.0), size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='population_total_yearly_income',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=5), default=(0.0, 0.0), size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='teacher_per_student',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=5), default=(0.0, 0.0), size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='unemployment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=5), default=(0.0, 0.0), size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sector',
            name='university_educated_population',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=(0, 0), size=None),
            preserve_default=False,
        ),
    ]
